var campus = {
	"watumull":{	
		"GndFloor" : [
			{
				"name" : "EXTC Classroom",
				"type" : "room",
				"location" : [175,45],
				"size": [35,35],
			},
	        {
				"name" : "",
				"type" : "door-d",
				"location" : [185,61],
				"size": [5,5],
			},
			{
				"name" : "FE Comps Classroom",
				"type" : "room",
				"location" : [175,15],
				"size": [35,35],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [185,50],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "passage",
				"location" : [135,15],
				"size": [40,60],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [162,75],
				"size": [10,10],
			},
			{
				"name" : "",
				"type" : "stairs-elev",
				"location" : [135,15],
				"size": [40,40],
			},
			{
				"name" : "Fire Extingusher Room",
				"type" : "c-passage",
				"location" : [115,15],
				"size": [20,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [135,40],
				"size": [5,5],
			},
			{
				"name" : "Ladies Washroom",
				"type" : "toilet",
				"location" : [95,15],
				"size": [20,15],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [115,35],
				"size": [5,5],
			},
			{
				"name" : "Staff Room",
				"type" : "room",
				"location" : [65,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [95,40],
				"size": [5,5],
			},
			{
				"name" : "FE EXTC Classroom",
				"type" : "room",
				"location" : [83,55],
				"size": [52,25],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [135,65],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "stairs",
				"location" : [64,55],
				"size": [20,20],
			},
			{
				"name" : "BEE/EXTC Lab",
				"type" : "room",
				"location" : [35,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [65,40],
				"size": [5,5],
			},
			{
				"name" : "Physics Lab",
				"type" : "room",
				"location" : [5,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [35,40],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "line",
				"location" : [4.9,35],
				"size": [0,20],
			},
		    {
				"name" : "Engg-Mechanics Lab",
				"type" : "room",
				"location" : [25,55],
				"size": [40,20],
			},
				{
				"name" : "",
				"type" : "door-d",
				"location" : [65,65],
				"size": [5,5],
			},
			{
				"name" : "Boys Washroom",
				"type" : "toilet",
				"location" : [5,55],
				"size": [20,20],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [30,65],
				"size": [5,5],
			},
		],
		"1stFloor" : [
			{
				"name" : "Principle Cabin",
				"type" : "room",
				"location" : [158,45],
				"size": [30,30],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [173,55],
				"size": [5,5],
			},
			{
				"name" : "Admission Department",
				"type" : "room",
				"location" : [158,15],
				"size": [30,30],
			},
		    {
				"name" : "",
				"type" : "door-d",
				"location" : [168,45],
				"size": [5,5],
			}, 
			{
				"name" : "",
				"type" : "stairs-elev",
				"location" : [118,15],
				"size": [40,40],
			},
			{
				"name" : "",
				"type" : "line",
				"location" : [118,65],
				"size": [40,0],
			},
			{
				"name" : "Teachers Washroom",
				"type" : "toilet",
				"location" : [95,15],
				"size": [23,15],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [121,35],
				"size": [5,5],
			},
			{
				"name" : "Vice Principle Cabin",
				"type" : "room",
				"location" : [65,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [98,40],
				"size": [5,5],
			},

			{
				"name" : "Profs. StaffRoom",
				"type" : "room",
				"location" : [85,55],
				"size": [33,20],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [121,65],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "stairs",
				"location" : [70,54],
				"size": [15,25],
			},
			{
				"name" : "BE Lab",
				"type" : "room",
				"location" : [30,15],
				"size": [35,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [68,40],
				"size": [5,5],
			},
			{
				"name" : "SE Lab",
				"type" : "room",
				"location" : [5,15],
				"size": [25,20],
			},
		    {
				"name" : "",
				"type" : "door-u",
				"location" : [33,40],
				"size": [5,5],
			},
			{
				"name" : "FE Computer Lab",
				"type" : "room",
				"location" : [30,55],
				"size": [40,20],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [42,65],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [73,65],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "line",
				"location" : [4.9,35],
				"size": [0,25],
			},
			{
				"name" : "Eng. Mechanics StaffRoom",
				"type" : "room",
				"location" : [5,55],
				"size": [25,20],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [33,65],
				"size": [5,5],
			},
		],
		"2ndFloor" : [
			{
				"name" : "Computer Lab",
				"type" : "room",
				"location" : [158,48],
				"size": [30,32],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [168,72],
				"size": [5,5],
			},
			{
				"name" : "EXTC StaffRoom",
				"type" : "room",
				"location" : [158,15],
				"size": [30,33],
			},
			    {
				"name" : "",
				"type" : "door-d",
				"location" : [168,50],
				"size": [5,5],
			}, 
			{
				"name" : "",
				"type" : "stairs-elev",
				"location" : [118,15],
				"size": [40,40],
			},	
			{
				"name" : "Computer Lab",
				"type" : "room",
				"location" : [118,55],
				"size": [40,25],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [145,65],
				"size": [5,5],
			},
			{
				"name" : "Library",
				"type" : "c-passage",
				"location" : [5,15],
				"size": [60,27],
			},
			{
				"name" : "Book Store",
				"type" : "c-passage",
				"location" : [65,15],
				"size": [53,27],
			},
			{
				"name" : "Library",
				"type" : "c-passage",
				"location" : [5,42],
				"size": [50,38],
			},
			{
				"name" : "Book Store",
				"type" : "c-passage",
				"location" : [77.5,42],
				"size": [40.5,38],
			},
			
			{
				"name" : "",
				"type" : "door-d",
				"location" : [87.5,54],
				"size": [5,5],
			},
			 
			{
				"name" : "",
				"type" : "door-u",
				"location" : [60,54],
				"size": [5,5],
			},
		
			{
				"name" : "",
				"type" : "stairs",
				"location" : [53.6,55],
				"size": [25,25],
			},
		
		],
		"3rdFloor" : [
			{
				"name" : "EXTC SE Classroom",
				"type" : "room",
				"location" : [158,50],
				"size": [30,30],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [168,63],
				"size": [5,5],
			},
			{
				"name" : "EXTC Electronics Lab",
				"type" : "room",
				"location" : [158,15],
				"size": [30,35],
			},
			    {
				"name" : "",
				"type" : "door-d",
				"location" : [168,52],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "stairs-elev",
				"location" : [118,15],
				"size": [40,40],
	        },
			{
				"name" : "Store Room",
				"type" : "room",
				"location" : [118,65],
				"size": [40,15],
			},
			 {
				"name" : "",
				"type" : "door-d",
				"location" : [145,75],
				"size": [5,5],
			},
			{
				"name" : "Electricity Room",
				"type" : "c-passage",
				"location" : [95,15],
				"size": [23,15],
			},
            {
				"name" : "",
				"type" : "door-u",
				"location" : [120,35],
				"size": [5,5],
			},
			{
				"name" : "EXTC TE Classroom",
				"type" : "room",
				"location" : [65,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [97,40],
				"size": [5,5],
			},
			{
				"name" : "BE EXTC Classroom",
				"type" : "room",
				"location" : [68,55],
				"size": [50,25],
			},
			 {
				"name" : "",
				"type" : "door-d",
				"location" : [120,65],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "stairs",
				"location" : [49,60],
				"size": [20,20],
			},
			{
				"name" : "DLDA/EXTC Lab",
				"type" : "room",
				"location" : [25,15],
				"size": [40,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [67,40],
				"size": [5,5],
			},
			{
				"name" : "BE Lab",
				"type" : "room",
				"location" : [5,15],
				"size": [20,65],
			},
            {
				"name" : "",
				"type" : "door-u",
				"location" : [30,55],
				"size": [5,5],
			},
			{
				"name" : "EXTC Lab",
				"type" : "room",
				"location" : [25,55],
				"size": [25,25],
			},
		    {
				"name" : "",
				"type" : "door-d",
				"location" : [52,65],
				"size": [5,5],
			},
		],
		"4thFloor" : [
			{
				"name" : "SE Comps Classroom",
				"type" : "room",
				"location" : [155,45],
				"size": [30,30],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [165,58],
				"size": [5,5],
			},
		
			{
				"name" : "Chemistry Lab",
				"type" : "room",
				"location" : [155,15],
				"size": [30,30],
			},
				{
				"name" : "",
				"type" : "door-d",
				"location" : [165,47],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "stairs-elev",
				"location" : [115,15],
				"size": [40,40],
			},
			{
				"name" : "Mathematics StaffRoom",
				"type" : "c-passage",
				"location" : [114.5,60],
				"size": [40.5,15],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [144,70],
				"size": [5,5],
			},
			{
				"name" : "Boys Washroom",
				"type" : "toilet",
				"location" : [95,15],
				"size": [20,15],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [117,35],
				"size": [5,5],
			},
			{
				"name" : "Store Room",
				"type" : "room",
				"location" : [65,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [97,40],
				"size": [5,5],
			},
			{
				"name" : "TE Comps Classroom",
				"type" : "room",
				"location" : [64.5,55],
				"size": [50,20],
			},
				{
				"name" : "",
				"type" : "door-d",
				"location" : [117,65],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "stairs",
				"location" : [45,55],
				"size": [21,20],
			},
			{
				"name" : "Classroom",
				"type" : "room",
				"location" : [35,15],
				"size": [30,20],
			},
				{
				"name" : "",
				"type" : "door-u",
				"location" : [67,40],
				"size": [5,5],
			},
			{
				"name" : "Eng. Drawing Lab",
				"type" : "room",
				"location" : [5,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [37,40],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "line",
				"location" : [4.9,35],
				"size": [0,25],
			},
			{
				"name" : "EXTC Lab",
				"type" : "room",
				"location" : [5,55],
				"size": [41.5,20],
			},
				{
				"name" : "",
				"type" : "door-d",
				"location" : [47,65],
				"size": [5,5],
			},
			
		],
		"5thFloor" : [
			{
				"name" : "BE Comps Classroom",
				"type" : "room",
				"location" : [95,45],
				"size": [30,30],
			},
				{
				"name" : "",
				"type" : "door-d",
				"location" : [105,58],
				"size": [5,5],
			},
		
			{
				"name" : "Comps Lab",
				"type" : "room",
				"location" : [95,15],
				"size": [30,30],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [105,47],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "stairs-elev",
				"location" : [55,15],
				"size": [40,40],
			},
			
			{
				"name" : "Exam Department",
				"type" : "c-passage",
				"location" : [55,60],
				"size": [40,15],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [83,70],
				"size": [5,5],
			},
			{
				"name" : "Girls Washroom",
				"type" : "toilet",
				"location" : [35,15],
				"size": [20,15],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [57,35],
				"size": [5,5],
			},
			{
				"name" : "StaffRoom",
				"type" : "c-passage",
				"location" : [5,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [37,40],
				"size": [5,5],
			},
            {
				"name" : "",
				"type" : "line",
				"location" : [4.9,35],
				"size": [0,25],
			},
			{
				"name" : "Girls Common Room",
				"type" : "c-passage",
				"location" : [5,55],
				"size": [50,20],
			},
				{
				"name" : "",
				"type" : "door-d",
				"location" : [57,65],
				"size": [5,5],
			},
			
		],
		"6thFloor" : [
		
			{
				"name" : "Auditorium Hall",
				"type" : "room",
				"location" : [95,15],
				"size": [30,60],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [105,62],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "stairs-elev",
				"location" : [55,15],
				"size": [40,40],
			},
			
			{
				"name" : "Placement Department",
				"type" : "room",
				"location" : [55,60],
				"size": [40,15],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [83,70],
				"size": [5,5],
			},
			{
				"name" : " Washroom",
				"type" : "toilet",
				"location" : [35,15],
				"size": [20,15],
			},
				{
				"name" : "",
				"type" : "door-u",
				"location" : [57,35],
				"size": [5,5],
			},
			{
				"name" : "StoreRoom",
				"type" : "c-passage",
				"location" : [5,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [37,40],
				"size": [5,5],
			},
            {
				"name" : "",
				"type" : "line",
				"location" : [4.9,35],
				"size": [0,25],
			},
			{
				"name" : "Boys Common Room",
				"type" : "c-passage",
				"location" : [5,55],
				"size": [50,20],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [57,65],
				"size": [5,5],
			},
			
		],
        "7thFloor" : [
		    {
				"name" : "Comps Lab2",
				"type" : "room",
				"location" : [95,45],
				"size": [30,30],
			},
				{
				"name" : "",
				"type" : "door-d",
				"location" : [105,58],
				"size": [5,5],
			},
		
			{
				"name" : "Comps Lab1",
				"type" : "room",
				"location" : [95,15],
				"size": [30,30],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [105,47],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "stairs-elev",
				"location" : [55,15],
				"size": [40,40],
			},
			
			{
				"name" : "Comps Lab StaffRoom",
				"type" : "c-passage",
				"location" : [55,60],
				"size": [40,15],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [83,70],
				"size": [5,5],
			},
			{
				"name" : " Washroom",
				"type" : "toilet",
				"location" : [35,15],
				"size": [20,15],
			},
				{
				"name" : "",
				"type" : "door-u",
				"location" : [57,35],
				"size": [5,5],
			},
			{
				"name" : "StoreRoom",
				"type" : "c-passage",
				"location" : [5,15],
				"size": [30,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [37,40],
				"size": [5,5],
			},
			 {
				"name" : "",
				"type" : "line",
				"location" : [4.9,35],
				"size": [0,25],
			},
			{
				"name" : "Comps Lab3",
				"type" : "room",
				"location" : [5,55],
				"size": [50,20],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [57,65],
				"size": [5,5],
			},
			
			
		],
	}
}
