var campus = {
	"watumull":{
		"d" : [
			{
				"name" : "",
				"type" : "line",
				"location" : [80,0],
				"size": [0,20],
			},
			{
				"name" : "",
				"type" : "line",
				"location" : [85,0],
				"size": [20,0],
			},
			{
				"name" : "",
				"type" : "stairs",
				"location" : [0,0],
				"size": [20,25],
			},
			{
				"name" : "",
				"type" : "toilet",
				"location" : [0,30],
				"size": [20,20],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [15,55],
				"size": [5,5],
			},
			{
				"name" : "EXTC Classroom",
				"type" : "room",
				"location" : [25,30],
				"size": [20,20],
			},
			{
				"name" : "",
				"type" : "stairs-elev",
				"location" : [30,0],
				"size": [35,30],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [43,40],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [50,47],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "door-d",
				"location" : [35,47],
				"size": [5,5],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [43,55],
				"size": [5,5],
			},
		],
		"g" : [
			{
				"name" : "EXTC Classroom",
				"type" : "room",
				"location" : [250,40],
				"size": [25,25],
			},
			{
				"name" : "FE Comps Classroom",
				"type" : "room",
				"location" : [250,15],
				"size": [25,25],
			},
			{
				"name" : "",
				"type" : "passage",
				"location" : [170,15],
				"size": [80,70],
			},
			{
				"name" : "",
				"type" : "door-u",
				"location" : [205,75],
				"size": [20,20],
			},
			{
				"name" : "",
				"type" : "room",
				"location" : [199,0],
				"size": [15,15],
			},
			{
				"name" : "Fire Extingusible Room",
				"type" : "room",
				"location" : [140,15],
				"size": [30,20],
			},
			{
				"name" : "Ladies Washroom",
				"type" : "room",
				"location" : [115,15],
				"size": [25,10],
			},
			{
				"name" : "Faculty Department",
				"type" : "room",
				"location" : [85,15],
				"size": [30,20],
			},
			{
				"name" : "FE EXTC Classroom",
				"type" : "room",
				"location" : [110,60],
				"size": [60,25],
			},
			{
				"name" : "Stairs",
				"type" : "room",
				"location" : [85,60],
				"size": [25,25],
			},
			{
				"name" : "BEE/EXTC Lab",
				"type" : "room",
				"location" : [45,15],
				"size": [40,20],
			},
			{
				"name" : "Physics Lab",
				"type" : "room",
				"location" : [5,15],
				"size": [40,20],
			},
			{
				"name" : "Eng Mechanics Lab",
				"type" : "room",
				"location" : [30,60],
				"size": [55,25],
			},
			{
				"name" : "Boys Washroom",
				"type" : "room",
				"location" : [5,60],
				"size": [25,25],
			},
		],
		"f1" : [
			{
				"name" : "Principle Cabin",
				"type" : "room",
				"location" : [250,50],
				"size": [30,30],
			},
			{
				"name" : "Admission Department",
				"type" : "room",
				"location" : [250,15],
				"size": [30,35],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [235,15],
				"size": [15,30],
			},
				{
				"name" : "Lift",
				"type" : "room",
				"location" : [215,30],
				"size": [20,15],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [200,15],
				"size": [15,30],
			},
				{
				"name" : "",
				"type" : "room",
				"location" : [200,45],
				"size": [50,20],
			},
				{
				"name" : "Teachers Washroom",
				"type" : "room",
				"location" : [177,15],
				"size": [23,15],
			},
				{
				"name" : "Vice Principle Cabin",
				"type" : "room",
				"location" : [147,15],
				"size": [30,27],
			},
				{
				"name" : "Profs. StaffRoom",
				"type" : "room",
				"location" : [162,55],
				"size": [38,25],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [147,55],
				"size": [15,25],
			},
				{
				"name" : "BE Lab",
				"type" : "room",
				"location" : [109,15],
				"size": [38,27],
			},
				{
				"name" : "SE Lab",
				"type" : "room",
				"location" : [71,15],
				"size": [38,27],
			},
				{
				"name" : "FE Computer Lab",
				"type" : "room",
				"location" : [97,55],
				"size": [50,25],
			},
				{
				"name" : "Eng. Mechanics StaffRoom",
				"type" : "room",
				"location" : [71,55],
				"size": [26,25],
			},
		],
		"f2" : [
			{
				"name" : "Computer Lab",
				"type" : "room",
				"location" : [250,50],
				"size": [30,30],
			},
			{
				"name" : "EXTC StaffRoom",
				"type" : "room",
				"location" : [250,15],
				"size": [30,35],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [235,15],
				"size": [15,30],
			},
				{
				"name" : "Lift",
				"type" : "room",
				"location" : [215,30],
				"size": [20,15],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [200,15],
				"size": [15,30],
			},
				{
				"name" : "Computer Lab",
				"type" : "room",
				"location" : [200,55],
				"size": [50,25],
			},
		
				{
				"name" : "Books Store",
				"type" : "room",
				"location" : [147,15],
				"size": [53,65],
			},
		
				{
				"name" : "Library",
				"type" : "room",
				"location" : [71,15],
				"size": [76,27],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [132,55],
				"size": [15,25],
			},
				{
				"name" : "Library",
				"type" : "room",
				"location" : [71,42],
				"size": [61,38],
			},
		],
		"f3" : [
			{
				"name" : "EXTC SE Classroom",
				"type" : "room",
				"location" : [250,50],
				"size": [30,30],
			},
			{
				"name" : "EXTC Electronics Lab",
				"type" : "room",
				"location" : [250,15],
				"size": [30,35],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [235,15],
				"size": [15,30],
			},
				{
				"name" : "Lift",
				"type" : "room",
				"location" : [215,30],
				"size": [20,15],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [200,15],
				"size": [15,30],
			},
				{
				"name" : "Store Room",
				"type" : "room",
				"location" : [200,65],
				"size": [50,15],
			},
				{
				"name" : "Electricity Room",
				"type" : "room",
				"location" : [177,15],
				"size": [23,15],
			},
				{
				"name" : "EXTC TE Classroom",
				"type" : "room",
				"location" : [147,15],
				"size": [30,27],
			},
				{
				"name" : "BE EXTC Classroom",
				"type" : "room",
				"location" : [147,55],
				"size": [53,25],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [132,55],
				"size": [15,25],
			},
				{
				"name" : "DLDA/EXTC Lab",
				"type" : "room",
				"location" : [96,15],
				"size": [51,27],
			},
				{
				"name" : "BE Lab",
				"type" : "room",
				"location" : [71,15],
				"size": [25,65],
			},
				{
				"name" : "EXTC Lab",
				"type" : "room",
				"location" : [96,55],
				"size": [37,25],
			},
		
		],
		"f4" : [
			{
				"name" : "SE Comps Classroom",
				"type" : "room",
				"location" : [250,50],
				"size": [30,30],
			},
			{
				"name" : "Chemistry Lab",
				"type" : "room",
				"location" : [250,15],
				"size": [30,35],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [235,15],
				"size": [15,30],
			},
				{
				"name" : "Lift",
				"type" : "room",
				"location" : [215,30],
				"size": [20,15],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [200,15],
				"size": [15,30],
			},
				{
				"name" : "Mathematics StaffRoom",
				"type" : "room",
				"location" : [200,60],
				"size": [50,20],
			},
				{
				"name" : "Boys Washroom",
				"type" : "room",
				"location" : [177,15],
				"size": [23,15],
			},
				{
				"name" : "Store Room",
				"type" : "room",
				"location" : [147,15],
				"size": [30,27],
			},
				{
				"name" : "TE Comps Classroom",
				"type" : "room",
				"location" : [147,55],
				"size": [53,25],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [132,55],
				"size": [15,25],
			},
				{
				"name" : "Classroom",
				"type" : "room",
				"location" : [109,15],
				"size": [38,27],
			},
				{
				"name" : "Eng. Drawing Lab",
				"type" : "room",
				"location" : [71,15],
				"size": [38,27],
			},
				{
				"name" : "EXTC Lab",
				"type" : "room",
				"location" : [71,55],
				"size": [76,25],
			},
			
		],
		"f5" : [
			{
				"name" : "BE Comps Classroom",
				"type" : "room",
				"location" : [150,50],
				"size": [30,30],
			},
			{
				"name" : "Comps Lab",
				"type" : "room",
				"location" : [150,15],
				"size": [30,35],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [135,15],
				"size": [15,30],
			},
				{
				"name" : "Lift",
				"type" : "room",
				"location" : [115,30],
				"size": [20,15],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [100,15],
				"size": [15,30],
			},
				{
				"name" : "Exam Department",
				"type" : "room",
				"location" : [100,60],
				"size": [50,20],
			},
				{
				"name" : "Girls Washroom",
				"type" : "room",
				"location" : [77,15],
				"size": [23,15],
			},
				{
				"name" : "StaffRoom",
				"type" : "room",
				"location" : [47,15],
				"size": [30,27],
			},
				{
				"name" : "Girls Common Room",
				"type" : "room",
				"location" : [47,55],
				"size": [53,25],
			},
			
		],
		"f6" : [
		
			{
				"name" : "Auditorium Hall",
				"type" : "room",
				"location" : [150,15],
				"size": [30,65],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [135,15],
				"size": [15,30],
			},
				{
				"name" : "Lift",
				"type" : "room",
				"location" : [115,30],
				"size": [20,15],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [100,15],
				"size": [15,30],
			},
				{
				"name" : "Placement Department",
				"type" : "room",
				"location" : [100,60],
				"size": [50,20],
			},
				{
				"name" : " Washroom",
				"type" : "room",
				"location" : [77,15],
				"size": [23,15],
			},
				{
				"name" : "StoreRoom",
				"type" : "room",
				"location" : [47,15],
				"size": [30,27],
			},
				{
				"name" : "Boys Common Room",
				"type" : "room",
				"location" : [47,55],
				"size": [53,25],
			},
			
		],
        "f7" : [
		    {
				"name" : "Comps Lab2",
				"type" : "room",
				"location" : [150,50],
				"size": [30,30],
			},
			{
				"name" : "Comps Lab1",
				"type" : "room",
				"location" : [150,15],
				"size": [30,35],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [135,15],
				"size": [15,30],
			},
				{
				"name" : "Lift",
				"type" : "room",
				"location" : [115,30],
				"size": [20,15],
			},
				{
				"name" : "Stairs",
				"type" : "room",
				"location" : [100,15],
				"size": [15,30],
			},
				{
				"name" : "Comps Lab StaffRoom",
				"type" : "room",
				"location" : [100,60],
				"size": [50,20],
			},
				{
				"name" : " Washroom",
				"type" : "room",
				"location" : [77,15],
				"size": [23,15],
			},
				{
				"name" : "StoreRoom",
				"type" : "room",
				"location" : [47,15],
				"size": [30,27],
			},
				{
				"name" : "Comps Lab3",
				"type" : "room",
				"location" : [47,55],
				"size": [53,25],
			},
			
		],
	}
}
